---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: postgresql 
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.10.201
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql